sylius_resource:
  resources:
    contelizer.subscription:
      driver: doctrine/orm
      classes:
        model: Acme\SyliusExamplePlugin\Entity\Subscription
        repository: Acme\SyliusExamplePlugin\Repository\SubscriptionRepository
        controller: Acme\SyliusExamplePlugin\Controller\SubscriptionController