acme_sylius_example_plugin_admin:
  resource: 'routing/admin.yml'
  prefix: /admin

acme_sylius_example_plugin_shop:
  resource: "routing/shop.yml"
  prefix: /{_locale}
  requirements:
    _locale: ^[a-z]{2}(?:_[A-Z]{2})?$

acme_sylius_example_plugin_account:
  resource: "routing/account.yml"
  prefix: /account