sylius_grid:
    grids:
        contelizer_admin_subscription:
            driver:
                name: doctrine/orm
                options:
                    class: Acme\SyliusExamplePlugin\Entity\Subscription
            fields:
                  channel:
                    type: twig
                    label: sylius.ui.channel
                    sortable: channel.code
                    options:
                      template: "@SyliusAdmin/Order/Grid/Field/channel.html.twig"
                  customer:
                    type: twig
                    label: sylius.ui.customer
                    sortable: customer.lastName
                    options:
                      template: "@SyliusAdmin/Order/Grid/Field/customer.html.twig"
                  cycles:
                    type: twig
                    label: app.ui.cycles
                    options:
                      template: "@SyliusAdmin/Subscription/Grid/Field/num.html.twig"
                  state:
                    type: twig
                    label: sylius.ui.state
                    sortable: ~
                    options:
                      template: "@SyliusUi/Grid/Field/state.html.twig"
                      vars:
                        labels: "@SyliusAdmin/Order/Label/State"
                  createdAt:
                    type: datetime
                    label: sylius.ui.date
                    options:
                      format: d-m-Y H:i:s
                  updatedAt:
                    type: datetime
                    label: sylius.ui.date
                    options:
                      format: d-m-Y H:i:s
            filters:
               createdAt:
                  type: string
                  label: sylius.ui.customer
                  options:
                    fields: [customer.email, customer.firstName, customer.lastName]
               date:
                  type: date
                  label: sylius.ui.date
            actions:
                item:
                    show:
                        type: show