contelizer_admin_subscription:
    resource: |
        alias: contelizer.subscription
        section: admin
        templates: SyliusAdminBundle:Subscription
        redirect: update
        grid: contelizer_admin_subscription
        vars:
            all:
                subheader: app.ui.supplier
            index:
                icon: 'sync'
    type: sylius.resource
admin_cancel_subscription:
    path: /subscription/cancel/{id}
    defaults:
        _controller: contelizer.controller.subscription:cancelSubscription