contelizer_admin_subscription:
    resource: |
        alias: contelizer.subscription
        section: admin
        templates: SyliusAdminBundle:Crud
        redirect: update
        grid: contelizer_admin_subscription
        vars:
            all:
                subheader: app.ui.supplier
            index:
                icon: 'file image outline'
    type: sylius.resource